# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"
  jetstack:    "https://charts.jetstack.io"

namespaces:
  metallb:
  metrics:
  cert-manager:

apps:
  metallb:
    chart: stable/metallb
    version: 0.9.7
    enabled: true
    namespace: metallb

  prometheus:
    chart: stable/prometheus
    version: 8.14.0
    enabled: true
    namespace: metrics
    set:
      rbac.create: true
      alertmanager.enabled: false
      pushgateway.enabled: false,
      networkPolicy.enabled: true
      server.retention: '7d'

  grafana:
    chart: stable/grafana
    version: 3.5.7
    enabled: true
    namespace: metrics
    valuesFiles:
     - values-grafana-datasources.yaml
    # - values-grafana-ingress.yaml
    # - values-grafana-github-oauth.yaml
    set:
      adminPassword: "$GRAFANA_ADMIN_PASSWD"
      #persistence.enabled: true
      #persistence.size: 10Mi
      sidecar.dashboards.enabled: true
      sidecar.dashboards.searchNamespace: ALL

  cert-manager:
    chart: jetstack/cert-manager
    version: v0.8.1
    enabled: true
    namespace: cert-manager
