# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"
  jetstack:    "https://charts.jetstack.io"

namespaces:
  metallb:
  metrics:
  cert-manager:

apps:
  metallb:
    chart: stable/metallb
    version: 0.11.2
    enabled: true
    namespace: metallb

  prometheus:
    chart: stable/prometheus
    version: 9.1.0
    enabled: true
    namespace: metrics
    set:
      rbac.create: true
      alertmanager.enabled: false
      pushgateway.enabled: false,
      networkPolicy.enabled: true
      server.retention: '7d'

  grafana:
    chart: stable/grafana
    version: 3.8.12
    enabled: true
    namespace: metrics
    valuesFiles:
     - values-grafana.yaml
     - values-grafana-datasources.yaml
     - values-grafana-ingress.yaml
     - values-grafana-github-oauth.yaml

  cert-manager:
    chart: jetstack/cert-manager
    version: v0.10.0
    enabled: true
    namespace: cert-manager
