# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  monitoring-grafana:

apps:
  grafana:
    chart: stable/grafana
    version: 4.4.0
    enabled: true
    namespace: monitoring-grafana
    valuesFiles:
     - values-grafana.yaml
     - values-grafana-datasources.yaml
     - values-grafana-ingress.yaml
     - values-grafana-github-oauth.yaml
