---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: metrics
  labels:
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server:80
      isDefault: true
      editable: false
    - name: loki
      type: loki
      access: proxy
      url: http://loki.loki:3100
      isDefault: false
      editable: false
