
releases:
  - name: prometheus
    namespace: default
    chart: stable/prometheus
    version: 7.1.3
    values:
    - values-prometheus.yaml

  - name: grafana
    namespace: default
    chart: stable/grafana
    version: 1.11.1
    values:
    - values-grafana.yaml
    set:
    - name: adminPassword
      value: {{ env "GRAFANA_ADMIN_PASSWD" | default "" | quote }}

  - name: traefik
    namespace: default
    chart: stable/traefik
    version: 1.55.1
    values:
    - values-traefik.yaml

  - name: metallb
    namespace: metallb-system
    chart: stable/metallb
    version: 0.8.3

  - name: metrics-server
    namespace: kube-system
    chart: stable/metrics-server
    version: 2.0.4
