# For use with Helmsman

helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"
  stagingrepo: "https://raw.githubusercontent.com/MichaelVL/contour-envoy-helm-chart/master/"

namespaces:
  metallb:
  contour-int:
  contour-ext:
  metrics-server:
  metrics:
  cert-manager:

apps:
  metallb:
    chart: stable/metallb
    version: 0.9.5
    enabled: true
    namespace: metallb

  contour-int:
    chart: "stagingrepo/contour"
    version: "0.2.5"
    enabled: true
    namespace: "contour-int"
    set:
      contour.ingressClassName: "internal"
      crd.create: false
      deployment.replicas: 1
      service.type: "NodePort"
      service.nodePorts.http: 31080
      service.nodePorts.https: 31443
  
  contour-ext:
    chart: "stagingrepo/contour"
    version: "0.2.5"
    enabled: true
    namespace: "contour-ext"
    set:
      contour.ingressClassName: "external"
      deployment.replicas: 1

  metrics-server:
    chart: stable/metrics-server
    version: 2.7.0
    enabled: true
    namespace: kube-system
#    set:
#      args:
#       - "--kubelet-insecure-tls"

  prometheus:
    chart: stable/prometheus
    version: 8.10.3
    enabled: true
    namespace: metrics
    set:
      rbac.create: true
      alertmanager.enabled: false
      pushgateway.enabled: false,
      networkPolicy.enabled: true
      server.retention: '7d'

  grafana:
    chart: stable/grafana
    version: 3.3.2
    enabled: true
    namespace: metrics
    set:
      adminPassword: "$GRAFANA_ADMIN_PASSWD"
      sidecar.datasources.enabled: true
      sidecar.dashboards.enabled: true
      sidecar.dashboards.searchNamespace: ALL
      ingress.enabled: true
      ingress.annotations."kubernetes\.io/ingress\.class": "internal"
      ingress.hosts[0]: ""

  cert-manager:
    chart: stable/cert-manager
    version: v0.6.7
    enabled: false
    namespace: cert-manager
