# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"
  jetstack:    "https://charts.jetstack.io"

namespaces:
  metallb:
  metrics-server:
  metrics:
  cert-manager:

apps:
  metallb:
    chart: stable/metallb
    version: 0.9.5
    enabled: true
    namespace: metallb

  metrics-server:
    chart: stable/metrics-server
    version: 2.7.0
    enabled: true
    namespace: kube-system
#    set:
#      args:
#       - "--kubelet-insecure-tls"

  prometheus:
    chart: stable/prometheus
    version: 8.10.3
    enabled: true
    namespace: metrics
    set:
      rbac.create: true
      alertmanager.enabled: false
      pushgateway.enabled: false,
      networkPolicy.enabled: true
      server.retention: '7d'

  grafana:
    chart: stable/grafana
    version: 3.3.2
    enabled: true
    namespace: metrics
    set:
      adminPassword: "$GRAFANA_ADMIN_PASSWD"
      sidecar.datasources.enabled: true
      sidecar.dashboards.enabled: true
      sidecar.dashboards.searchNamespace: ALL
      #ingress.enabled: true
      #ingress.annotations."kubernetes\.io/ingress\.class": "internal"
      #ingress.hosts[0]: ""

  cert-manager:
    chart: jetstack/cert-manager
    version: v0.8.0
    enabled: false
    namespace: cert-manager
