# For use with Helmsman

helmRepos:
  loki: "https://grafana.github.io/loki/charts"

namespaces:
  loki:

apps:
  promtail:
    chart: loki/promtail
    version: 0.8.0
    enabled: true
    namespace: loki
    priority: -2
    set:
      loki.serviceName: loki

  loki:
    chart: loki/loki
    version: 0.10.0
    enabled: true
    namespace: loki
    priority: -1
    set:
      persistence.enabled: true
      persistence.storageClassName: ""
      persistence.size: 10Gi
      config.table_manager.retention_deletes_enabled: true
      config.table_manager.retention_period: 5m