# For use with Helmsman

helmRepos:
  loki: "https://grafana.github.io/loki/charts"

namespaces:
  monitoring-loki:

apps:
  loki:
    chart: loki/loki
    version: 0.22.0
    enabled: true
    namespace: monitoring-loki
    priority: -1
    valuesFiles:
     - values-loki.yaml
