apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb
  name: metallb-config
data:
  config: |
    address-pools:
    - name: example-vip-pool
      protocol: layer2
      addresses:
      - 192.168.2.220-192.168.2.229
