# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  metrics-server:

apps:
  metrics-server:
    chart: stable/metrics-server
    version: 2.9.0
    enabled: true
    namespace: metrics-server
    wait: true
    valuesFiles:
     - values-metrics-server.yaml
