# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  kube-system:

apps:
  metrics-server:
    chart: stable/metrics-server
    version: 2.8.7
    enabled: true
    namespace: kube-system
    valuesFiles:
     - values-metrics-server.yaml
