# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"
  jetstack:    "https://charts.jetstack.io"

namespaces:
  metrics-server:

apps:
  metrics-server:
    chart: stable/metrics-server
    version: 2.8.2
    enabled: true
    namespace: kube-system
    set:
      args[0]: "--kubelet-insecure-tls"
