# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  kube-system:
    useTiller: true

apps:
  metrics-server:
    chart: stable/metrics-server
    version: 2.8.8
    enabled: true
    namespace: kube-system
    wait: true
    valuesFiles:
     - values-metrics-server.yaml
