# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  metrics:

apps:
  metrics-server:
    chart: stable/metrics-server
    version: 2.8.7
    enabled: true
    namespace: metrics
    set:
      args[0]: "--kubelet-insecure-tls"
