# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  nfs-storage:

apps:
  nfs-server-provisioner:
    chart: stable/nfs-server-provisioner
    version: 0.3.2
    enabled: true
    namespace: nfs-storage
    valuesFiles:
     - values-nfs-server-provisioner.yaml
