# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  oauth2proxy:

apps:
  oauth2proxy:
    chart: stable/oauth2-proxy
    version: 0.15.0
    enabled: true
    namespace: oauth2proxy
    valuesFiles:
     - values-oauth2-proxy.yaml
