# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  monitoring-prom-adapter:

apps:
  prom-adapter:
    chart: stable/prometheus-adapter
    version: 2.0.1
    enabled: true
    namespace: monitoring-prom-adapter
    valuesFiles:
     - values-prometheus-adapter.yaml
