# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  monitoring-prometheus:

apps:
  prometheus:
    chart: stable/prometheus
    version: 11.0.2
    enabled: true
    namespace: monitoring-prometheus
    valuesFiles:
     - values-prometheus.yaml
     - values-prometheus-alerting-rules.yaml
