# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  metrics:

apps:
  prometheus:
    chart: stable/prometheus
    version: 9.1.1
    enabled: true
    namespace: metrics
    set:
      rbac.create: true
      alertmanager.enabled: false
      pushgateway.enabled: false,
      networkPolicy.enabled: true
      server.retention: '7d'
