# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  metrics:

apps:
  prometheus:
    chart: stable/prometheus
    version: 9.2.0
    enabled: true
    namespace: metrics
    valuesFiles:
     - values-prometheus.yaml
