# For use with Helmsman

helmRepos:
  loki: "https://grafana.github.io/loki/charts"

namespaces:
  monitoring-promtail:

apps:
  promtail:
    chart: loki/promtail
    version: 0.19.1
    enabled: true
    namespace: monitoring-promtail
    priority: -2
    valuesFiles:
     - values-promtail.yaml
