# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  kube-system:

apps:
  sealed-secrets:
    chart: stable/sealed-secrets
    version: 1.7.5
    enabled: true
    namespace: kube-system
    valuesFiles:
     - values-sealed-secrets.yaml
