# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  sealed-secrets:

apps:
  flux:
    chart: stable/sealed-secrets
    version: 1.6.1
    enabled: true
    namespace: sealed-secrets
