# For use with Helmsman

helmRepos:
  stable:      "https://kubernetes-charts.storage.googleapis.com"

namespaces:
  traefik:

apps:
  traefik:
    chart: stable/traefik
    version: 1.78.2
    enabled: true
    namespace: traefik
    valuesFiles:
    - values-traefik.yaml
