grafana.ini:
  auth.github:
    enabled: true
    allow_sign_up: true
    client_id: $OAUTH_CLIENT_ID
    client_secret: $OAUTH_CLIENT_SECRET
    scopes: user:email,read:org
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    api_url: https://api.github.com/user
#    team_ids:
    allowed_organizations: $OAUTH_ALLOWED_ORGS
