datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.metrics:80
      isDefault: true
      editable: false
    - name: loki
      type: loki
      access: proxy
      url: http://loki.loki:3100
      isDefault: false
      editable: false
