persistence:
  enabled: true
  storageClass: "-"
  size: 200Gi
storageClass:
  defaultClass: true
nodeSelector:
  #"kubernetes.io/hostname": $NFS_STORAGE_PROVISIONER_HOSTNAME
  storage-node: '1'
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
