grafana.ini:
  server:
    root_url: "https://grafana.$DNS_DOMAIN"
adminPassword: "$GRAFANA_ADMIN_PASSWD"
#persistence:
#  enabled: true
#  size: 10Mi
sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
