rbac:
  create: true
alertmanager:
  enabled: true
pushgateway:
  enabled: false
networkPolicy:
  enabled: true
server:
  retention: '7d'
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
alertmanager:
  persistentVolume:
    enabled: false
  resources:
    limits:
      cpu: 10m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 32Mi
  service:
    type: NodePort
    nodePort: 30000
nodeExporter:
  tolerations:
  - key: "node-role.kubernetes.io/master"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/foo"
    effect: "NoSchedule"
  resources:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 50m
      memory: 8Mi
kubeStateMetrics:
  resources:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 50m
      memory: 8Mi
