persistence:
  enabled: true
  storageClassName: ""
  size: 10Gi
config:
  table_manager:
    retention_deletes_enabled: true
    # Must be a multiple of index.period, which is 168h
    retention_period: 336h
resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 32Mi
