master:
  installPlugins:
    - kubernetes
    - workflow-job
    - workflow-aggregator
    - credentials-binding
    - git
    - configuration-as-code
    - blueocean
    - ssh-slaves
    - docker-plugin
